apiVersion: apps/v1
kind: Deployment
metadata:
  name: beetroot
  labels:
    app: beetroot
spec:
  selector:
    matchLabels:
      app: beetroot
  template:
    metadata:
      labels:
        app: beetroot
    spec:
      containers:
      - name: beetroot
        image: samueldevops22/k8sbeetroot:beet
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:  
  name: service-for-beetroot
spec:
  type: NodePort
  selector:
    app: beetroot
  ports:
  - port: 8080
    nodePort: 30001
