apiVersion: v1
kind: Service
metadata:
  labels:
    app: caddy
  name: caddy
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: caddy
  type: NodePort
